BoxConfigAccountBundle:
    resource: "@BoxConfigAccountBundle/Resources/config/routing.yml"
    prefix:   /

BoxConfigDefaultBundle:
    resource: "@BoxConfigDefaultBundle/Resources/config/routing.yml"
    prefix:   /
