BoxConfigDefaultBundle_default:
    resource: "@BoxConfigDefaultBundle/Resources/config/routing/default.yml"
    pattern:  /

BoxConfigDefaultBundle_widget:
    resource: "@BoxConfigDefaultBundle/Resources/config/routing/widget.yml"
    prefix:  /widget
