BoxConfigBoxBundle_software:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/software.yml"
    prefix:   /software

BoxConfigBoxBundle_softwarecategory:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/softwarecategory.yml"
    prefix:   /softwarecategory

BoxConfigBoxBundle_operatingsystem:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/operatingsystem.yml"
    prefix:   /operatingsystem

BoxConfigBoxBundle_configuration:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/configuration.yml"
    prefix:   /configuration

BoxConfigBoxBundle_machine:
    resource: "@BoxConfigBoxBundle/Resources/config/routing/machine.yml"
    prefix:   /machine