parameters:
#    box_config_box.example.class: BoxConfig\BoxBundle\Example

services:
#    box_config_box.example:
#        class: %box_config_box.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
