parameters:
#    box_config_account.example.class: BoxConfig\AccountBundle\Example

services:
#    box_config_account.example:
#        class: %box_config_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
