BoxConfigDefaultBundle_sidebar_top:
    pattern:  /top/{slug}
    defaults: { _controller: BoxConfigDefaultBundle:Sidebar:top }

BoxConfigDefaultBundle_sidebar_register:
    pattern:  /register
    defaults: { _controller: BoxConfigDefaultBundle:Sidebar:register }
