BoxConfigDefaultBundle_widget_top:
    pattern:  /top/{slug}
    defaults: { _controller: BoxConfigDefaultBundle:Widget:top }

BoxConfigDefaultBundle_widget_register:
    pattern:  /register
    defaults: { _controller: BoxConfigDefaultBundle:Widget:register }

BoxConfigDefaultBundle_widget_tip:
    pattern:  /tip
    defaults: { _controller: BoxConfigDefaultBundle:Widget:tip }

BoxConfigDefaultBundle_widget_userpanel:
    pattern:  /userpanel
    defaults: { _controller: BoxConfigDefaultBundle:Widget:userpanel }

BoxConfigDefaultBundle_widget_adminpanel:
    pattern:  /adminpanel
    defaults: { _controller: BoxConfigDefaultBundle:Widget:adminpanel }

BoxConfigDefaultBundle_widget_matchconfig:
    pattern:  /match/config
    defaults: { _controller: BoxConfigDefaultBundle:Widget:matchconfig }

BoxConfigDefaultBundle_widget_matchmachine:
    pattern:  /match/machine
    defaults: { _controller: BoxConfigDefaultBundle:Widget:matchmachine }

