BoxConfigDefaultBundle_widget_top:
    pattern:  /top/{slug}
    defaults: { _controller: BoxConfigDefaultBundle:Widget:top }

BoxConfigDefaultBundle_widget_register:
    pattern:  /register
    defaults: { _controller: BoxConfigDefaultBundle:Widget:register }

BoxConfigDefaultBundle_widget_tip:
    pattern:  /tip
    defaults: { _controller: BoxConfigDefaultBundle:Widget:tip }

BoxConfigDefaultBundle_widget_controlpanel:
    pattern:  /controlpanel
    defaults: { _controller: BoxConfigDefaultBundle:Widget:controlpanel }

BoxConfigDefaultBundle_widget_matchmachine:
    pattern:  /match/machine
    defaults: { _controller: BoxConfigDefaultBundle:Widget:matchmachine }

