parameters:
#    box_config_default.example.class: BoxConfig\Bundle\DefaultBundle\Example

services:
#    box_config_default.example:
#        class: %box_config_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
