configuration:
    pattern:  /
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:index" }

configuration_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:show" }

configuration_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:new" }

configuration_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:create" }
    requirements: { _method: post }

configuration_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:edit" }

configuration_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:update" }
    requirements: { _method: post }

configuration_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigBoxBundle:Configuration:delete" }
    requirements: { _method: post }
