machine:
    pattern:  /
    defaults: { _controller: "BoxConfigBoxBundle:Machine:index" }

machine_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoxConfigBoxBundle:Machine:show" }

machine_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigBoxBundle:Machine:new" }

machine_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigBoxBundle:Machine:create" }
    requirements: { _method: post }

machine_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigBoxBundle:Machine:edit" }

machine_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigBoxBundle:Machine:update" }
    requirements: { _method: post }

machine_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigBoxBundle:Machine:delete" }
    requirements: { _method: post }
