softwarecategory:
    pattern:  /
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:index" }

softwarecategory_show:
    pattern:  /{id}/show
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:show" }

softwarecategory_new:
    pattern:  /new
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:new" }

softwarecategory_create:
    pattern:  /create
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:create" }
    requirements: { _method: post }

softwarecategory_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:edit" }

softwarecategory_update:
    pattern:  /{id}/update
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:update" }
    requirements: { _method: post }

softwarecategory_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "BoxConfigBoxBundle:SoftwareCategory:delete" }
    requirements: { _method: post }
